(define (sum term a next b)
  (if (> a b)
    0
    (+ (term a)
       (sum term (next a) next b))))

(define (integral f a b dx)
  (define (add-dx x)
    (+ x dx))
  (* (sum f (+ a (/ dx 2.0)) add-dx b)
     dx))

(define (simpson f a b n)
  (let ((h (/ (- b a) n )))
    (define (y k) (f (+ a (* k h))))
    (define (term k)
      (* (y k)
         (cond ((or (= k 0) (= k n)) 1)
               ((even? k) 2)
               (else 4))))
    (* (/ h 3) (sum term 0 (lambda (x) (+ x 1)) n))))

(integral cube 0 1 0.001)
(simpson  cube 0 1 10)
(simpson  cube 0 1 100)
(simpson  cube 0 1 10000)
